---
title: Learning Resources
order: 1
fig-align: center
fig-cap-location: top
sidebar: false
---

A collection of self-guided learning resources created by others.
  
### Languages and Programming

[How to Learn to Code](https://www.youtube.com/watch?v=mvK0UzFNw1Q) -- A 5 minute video on how to approach programming, either learning theory, soliciting advice, OR (hint hint) *problem solving*.

[Python Course: Programming for Everybody (Getting Started with Python)](https://online.umich.edu/courses/programming-for-everybody-getting-started-with-python/) -- A terrific free course by the University of Michigan to learn the basics of programming in Python, with no prerequisites. 

[Biopython Course: Bioinformatics with Biopython](https://www.youtube.com/watch?v=ocA2IMe7dpA&list=PLhYDP66xNTKRdtUM8ekEmq1fC0mosXrgn&index=15) -- A 1-hour YouTube course that covers some common uses of biopython. Biopython is a set of tools for biological computaiton that is written in Python. It has many useful functions for processing and working with sequence files. 

[Python Cheatsheet](https://www.pythoncheatsheet.org/) -- A quick-reference, cheatsheet-styled website for common tasks/tricks in python. Helpful for beginners and power-users.

[R Course: swirl - learn R, in R](https://swirlstats.com/) -- Super cool way to learn R programming and datascience interactively, at your own pace, and in the R console. There is a library of courses you can learn from.

[R Course: Data Analysis using R](https://www.youtube.com/playlist?list=PLhR2Go-lh6X4fCAa3c_TBAjZD5A25s7fo) -- A comprehensive and high quality YouTube based course by Dr. Danny Arends (with videos, access to lectures, assignments, and answers) for those within minimal to no previous programming experience. This might be one of the best courses available.

[R for Data Science](https://r4ds.had.co.nz/index.html) -- A website for the "R for Data Science" book, with a focus on how to perform data science with R, from data exploration (visualization, workflow, working with tidy data, scripting), wrangling, modeling, and communicating results (R markdown).

[R Cheatsheet](https://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf) -- A quick-refrence cheatsheet for R.

[Unix Book: Unix Workbench](https://seankross.com/the-unix-workbench/introduction.html) -- A website (book) for those new to Unix-like operating systems and working at the command-line. This book covers unix and command-line basics, as well as introductory bash programming concepts (math, variables, loops, input/output, arrays, pbraces, functions), and writing programs. As a nice bonus, it also gives brief introductions to Git, GitHub, and Cloud Computing. 

[Bash Reference: bash-guide](https://github.com/Idnan/bash-guide) -- Common commands, with some minimal examples.

[Julia Course: Zero-to-Hero Julia Workshop](https://github.com/Datseris/Zero2Hero-JuliaWorkshop) -- Two day intensive, recorded ([YouTube](https://www.youtube.com/watch?v=Fi7Pf2NveH0)), workshop on the programming language, Julia. This workshop is intended for beginners. Julia is a programming language designed for scientific computing, to be quick, but also readable and high-level like Python. 

### Plotting and Visualizations

[Data Visualization with R](https://rkabacoff.github.io/datavis/) -- A Web-based book focused on data visualization and plotting with R. It covers data importing, cleaning, using plotting libraries (ggplot2), customizing plots, interactive visualization, and more.

[Shiny Cheatsheet](https://shiny.rstudio.com/images/shiny-cheatsheet.pdf) -- A quick reference cheatsheet for creating interactive web apps with shiny.

[Plotting with Python]  

[Interactive Visualizations with Plotly]  

### Single-Cell Analyses
[RNA-seq tutorial]  

[ATAC-seq tutorial]

### Proteomics

### Imaging Analysis
[Segmentation]

### CRISPR Analysis
[Pooled Screen]

### Workflow Managers
[Nexflow]  

[Snakemake]  

[Galaxy]

### Reproducibility
[Posit]  

[Posit Cheatsheets](https://posit.co/resources/cheatsheets/?type=posit-cheatsheets/) -- An amazing list of cheatsheets for eveyrthing rmarkdown, shiny, reticulate, stringr, readr, sparkly, tidyr, dplyr, ggplot2, and more.

[Jupyterlab and Notebooks]

### Cloud Computing
[]  
[]  
[]  

### ML/AI


### General Bioinformatics
[Rosalind](https://rosalind.info/problems/locations/) -- a great resource to learn about bioinformatics (including algorithms) and programming by problem-solving.


### Statistics

